name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 10
      - uses: JS-DevTools/npm-publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
